version: "3.8"
services:
  car:
    build: ./car
    container_name: service-car
    working_dir: /var/www
    volumes:
      - ./car:/var/www
    ports:
      - 5000:5000
    environment:
      FLASK_ENV: development
    networks:
      - app-network